### ISSUE TITLE
能否增加一个清零数据功能？

### ISSUE THREAD

**Issue by nasaboy** [sfpprxy/portmon#2]
能否增加一个清零数据功能？
手动清零数据还是弄不太懂具体怎么操作。

**Comment by nasaboy** [comment]
已经找到手动清零的方法了

**Comment by sfpprxy** [comment]
> 已经找到手动清零的方法了

请教一下你手动清零的流程是？

**Comment by nasaboy** [comment]
> > 已经找到手动清零的方法了
> 
> 
> 
> 请教一下你手动清零的流程是？

先停止服务，然后把data删除，重置iptables，开启服务就可以了。
