### ISSUE TITLE
偶尔卡死无法curl出数据

### ISSUE THREAD

**Issue by nasaboy** [sfpprxy/portmon#3]
今天刚好遇到了，看了下service status里面好像有错误提示，麻烦帮忙看看。
Apr 05 13:03:28 robot python3[6583]: @ÀrÀv
Apr 05 13:03:28 robot python3[6583]: ¾
Apr 05 13:03:28 robot python3[6583]: ½À" 400 -
Apr 05 13:03:28 robot python3[6583]: 47.102.184.30 - - [05/Apr/2020 13:03:28] "GET /HNAP1 HTTP/1.1" 404 -
Apr 05 13:03:28 robot python3[6583]: 47.102.184.30 - - [05/Apr/2020 13:03:28] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03\x0ejQüMÍ\x89¦9')
Apr 05 13:03:28 robot python3[6583]: [46B blob data]
Apr 05 13:03:28 robot python3[6583]: [1B blob data]
Apr 05 13:03:28 robot python3[6583]: [25B blob data]
Apr 05 13:03:28 robot python3[6583]: 47.102.184.30 - - [05/Apr/2020 13:03:28] "GET /nmaplowercheck1586063006 HTTP/1.1" 404 -
Apr 05 13:03:28 robot python3[6583]: 47.102.184.30 - - [05/Apr/2020 13:03:28] code 400, message Bad request syntax ("\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03æbp\x05Ô\x052\x19µ\x90\x1dÜü\x8a_bÐ×S\x89)\x015\x88°ÇËKþ\x82Cè Ô\x83k\x165P0«¼
eïÙ0G#\x0e¬ÿ8{Ë\x12]\xad9ßÝ(6\x0c\x89\x85\x00\x9c\x13\x02\x13\x03\x13\x01\x003\x009\x005\x00/À,À0\x00£\x00\x9fÌ©Ì¨ÌªÀ¯À\xadÀ£À\x9fÀ]ÀaÀWÀSÀ+À/\x00¢\x00\x9eÀ®À¬À¢À\x9eÀ\\À`ÀVÀRÀ$À(\x00k\x00jÀsÀw\x00Ä\x00ÃÀ#À'\x00g\x00@ÀrÀv\x00¾\x00½À")

**Comment by sfpprxy** [comment]
今天找到了原因并复现成功了。

原因：
portmon所使用python内置HTTPServer的问题，新建的TCP连接如果是与portmon的同端口并且不close，会导致HTTPServer的accept阻塞。

复现流程：
1. 本地使用 telnet localhost 9000 等待连接建立成功
2. 本地起另一个终端 curl localhost:9000
3. 发现无法curl出数据，表现为curl命令阻塞

准备换个web server替换掉内置的。

**Comment by sfpprxy** [comment]
已修复 2fc96b60cdd3f5c8f1dabea31ce36343b04056bc
请使用 uninstall.sh & install.sh 重新安装
