### ISSUE TITLE
新版还是会偶尔卡死curl不出数据

### ISSUE THREAD

**Issue by nasaboy** [sfpprxy/portmon#4]
新版还是会偶尔卡死curl不出数据，
service portmon status里面没有提示什么错误，restart以后正常。
提示这个curl: (7) Failed to connect to 161.*.*.* port 9000: Timed out，服务器是正常的。

**Comment by sfpprxy** [comment]
d918bc22d9d1d7a29114ff3c94a68e1d29a5c5a1 把python自带的http server换掉了，观察了一段时间没有遇到了，如果再次复现了请reopen这个issue。

**Comment by nasaboy** [comment]
新版安装以后，反正整个都不能正常工作了，curl倒是正常了，但是系统里面的端口流量数据不更新了，看了一下iptables没有加入监控指定端口的流量。

**Comment by sfpprxy** [comment]
已修复 d918bc22d9d1d7a29114ff3c94a68e1d29a5c5a1
请使用 uninstall.sh & install.sh 重新安装
