### ISSUE TITLE
新版无法正常工作

### ISSUE THREAD

**Issue by nasaboy** [sfpprxy/portmon#5]
最新版安装以后 反倒无法正常工作了
1 安装以后指定端口后，不会更新端口的流量信息，我用iptable -nxvL看了下，指定的端口没有加入到规则里面
2  如果之前有~/.portmon 下有data和portmon.log 这两个文件里面有数据，会导致程序出错，curl出来的数据变成错误500
 <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 500 Internal Server Error</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans-serif;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 500 Internal Server Error</h1>
            <p>Sorry, the requested URL <tt>&#039;http://**.**.152.200:9000/&#039;</tt>
               caused an error:</p>
            <pre>Internal Server Error</pre>
        </body>
    </html>
@sfpprxy

**Comment by sfpprxy** [comment]
portmon.log 能提供吗？

**Comment by nasaboy** [comment]
更新了你最新的版本，正常了。

**Comment by sfpprxy** [comment]
感谢反馈。
