### ISSUE TITLE
端口被扫描占用后，curl不出数据

### ISSUE THREAD

**Issue by nasaboy** [sfpprxy/portmon#6]
curl不出数据，我看了一下log，看不出有什么异常，然后用tcping 服务器ip 发现9000端口无法ping通
然后在服务器上ss sport = 9000，发现9000端口被一个阿里云的ip连接占用了。
感觉这应该是导致curl不出数据的原因
![微信截图_20200718211901](https://user-images.githubusercontent.com/5997682/87853421-75cfe100-c93c-11ea-85a5-fe30239db45b.png)

**Comment by sfpprxy** [comment]
~/.portmon/portmon.ini 可以修改默认的监听端口

**Comment by nasaboy** [comment]
好的，我怕修改了，还是会来扫，又出现一样的状况。

**Comment by sfpprxy** [comment]
请问把来自这个阿里云ip的连接关闭后还会出现curl不出的现象么？curl不出具体表现为curl命令阻塞无内容返回么？

**Comment by nasaboy** [comment]
我把端口修改成8443，阿里云的ip还是会来扫。curl出现这个错误提示“curl: (7) Failed to connect to 149.129.**.*** port 8443: Timed out”
service restart后可以正常curl数据。

**Comment by sfpprxy** [comment]
原因如下(本项目使用了bottle):
https://github.com/bottlepy/bottle/issues/904

如果不重启应用的话可以通过
ss -K dst 47.103.155.228
来关闭与这个IP的连接

或者使用Fail2ban等工具屏蔽它的扫描

我这边会研究下怎么自动关闭这些无用的连接。

**Comment by nasaboy** [comment]
好的，谢谢提供的方法。

**Comment by sfpprxy** [comment]
1564da428dfa4457776f7dc8ecc498cac6ec2edf 解决了这个问题，更新即可。

**Comment by nasaboy** [comment]
又引入了一个新的问题，curl出来的数据不更新，一直停留在某个数值，每restart一次，数值才会变。
